import { useState } from 'react';
import { useAuthContext } from '../hooks/useAuthContext';
import jsPDF from 'jspdf';
import 'jspdf-autotable';

const Reports = () => {
  const { user } = useAuthContext();
  const [startDate, setStartDate] = useState('');
  const [endDate, setEndDate] = useState('');
  const [reportData, setReportData] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  // Check if user is admin
  if (!user || user.role !== 'admin') {
    return (
      <div className="reports-container" style={{ padding: '20px', textAlign: 'center' }}>
        <h2>Access Denied</h2>
        <p>Only administrators can access reports.</p>
      </div>
    );
  }

  const generateReport = async () => {
    if (!startDate || !endDate) {
      setError('Please select both start and end dates');
      return;
    }

    if (new Date(startDate) > new Date(endDate)) {
      setError('Start date cannot be greater than end date');
      return;
    }

    setLoading(true);
    setError('');

    try {
      const apiUrl = process.env.REACT_APP_API_URL;
      const response = await fetch(`${apiUrl}/api/reports?startDate=${startDate}&endDate=${endDate}`, {
        headers: {
          'Authorization': `Bearer ${user.token}`
        }
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.error || 'Failed to generate report');
      }

      const data = await response.json();
      setReportData(data);
    } catch (error) {
      console.error('Error generating report:', error);
      setError(error.message || 'Failed to generate report');
    } finally {
      setLoading(false);
    }
  };

  const downloadPDF = async () => {
    if (!reportData) {
      setError('No report data available to download');
      return;
    }

    try {
      // Create new PDF document using static import
      const doc = new jsPDF();
      const pageWidth = doc.internal.pageSize.getWidth();
      
      // Company header
      doc.setFontSize(20);
      doc.setFont('helvetica', 'bold');
      doc.text('Inventory Management System', pageWidth / 2, 20, { align: 'center' });
      
      doc.setFontSize(16);
      doc.setFont('helvetica', 'normal');
      doc.text('Business Report', pageWidth / 2, 30, { align: 'center' });
      
      // Report details
      doc.setFontSize(12);
      const startDateFormatted = new Date(startDate).toLocaleDateString();
      const endDateFormatted = new Date(endDate).toLocaleDateString();
      const generatedDate = new Date().toLocaleDateString();
      const generatedTime = new Date().toLocaleTimeString();
      
      doc.text(`Report Period: ${startDateFormatted} - ${endDateFormatted}`, 20, 45);
      doc.text(`Generated on: ${generatedDate} at ${generatedTime}`, 20, 55);
      doc.text(`Generated by: ${user.name || 'Admin'}`, 20, 65);

      let yPosition = 80;

      // Summary Section
      doc.setFontSize(14);
      doc.setFont('helvetica', 'bold');
      doc.text('Summary', 20, yPosition);
      yPosition += 10;

      doc.setFontSize(11);
      doc.setFont('helvetica', 'normal');
      doc.text(`Total Stock Added: ${reportData.summary.totalStockAdded} items`, 20, yPosition);
      yPosition += 7;
      doc.text(`Total Sales Amount: S$${reportData.summary.totalSalesAmount.toFixed(2)}`, 20, yPosition);
      yPosition += 7;
      doc.text(`Total Items Sold: ${reportData.summary.totalItemsSold}`, 20, yPosition);
      yPosition += 7;
      doc.text(`Number of Orders: ${reportData.summary.numberOfOrders}`, 20, yPosition);
      yPosition += 15;

      // Stock Additions Section
      const totalStockItems = (reportData.inventory.items?.length || 0) + (reportData.purchases.items?.length || 0);
      
      if (totalStockItems > 0) {
        doc.setFontSize(14);
        doc.setFont('helvetica', 'bold');
        doc.text('Stock Additions', 20, yPosition);
        yPosition += 10;

        const stockData = [];
        
        // Add inventory items
        if (reportData.inventory.items && reportData.inventory.items.length > 0) {
          reportData.inventory.items.forEach(item => {
            stockData.push([
              item.name || 'Unknown',
              (item.quantity || 0).toString(),
              new Date(item.dateAdded).toLocaleDateString(),
              item.supplier || 'N/A',
              'New Item'
            ]);
          });
        }
        
        // Add purchase items
        if (reportData.purchases.items && reportData.purchases.items.length > 0) {
          reportData.purchases.items.forEach(item => {
            stockData.push([
              item.name || 'Unknown',
              (item.quantity || 0).toString(),
              new Date(item.dateAdded).toLocaleDateString(),
              item.supplier || 'N/A',
              'Purchase'
            ]);
          });
        }

        if (stockData.length > 0) {
          // Check if autoTable is available
          if (typeof doc.autoTable === 'function') {
            doc.autoTable({
              head: [['Item Name', 'Quantity', 'Date Added', 'Supplier', 'Type']],
              body: stockData,
              startY: yPosition,
              styles: { fontSize: 9 },
              headStyles: { fillColor: [66, 139, 202] },
              alternateRowStyles: { fillColor: [245, 245, 245] }
            });
            yPosition = doc.lastAutoTable.finalY + 15;
          } else {
            // Fallback: render as simple text if autoTable is not available
            doc.setFontSize(10);
            doc.setFont('helvetica', 'normal');
            stockData.forEach(row => {
              if (yPosition > 270) {
                doc.addPage();
                yPosition = 20;
              }
              doc.text(`• ${row[0]} - Qty: ${row[1]} - Date: ${row[2]} - Type: ${row[4]}`, 20, yPosition);
              yPosition += 6;
            });
            yPosition += 10;
          }
        }
      }

      // Check if we need a new page
      if (yPosition > 250) {
        doc.addPage();
        yPosition = 20;
      }

      // Sales Section
      if (reportData.sales.orders && reportData.sales.orders.length > 0) {
        doc.setFontSize(14);
        doc.setFont('helvetica', 'bold');
        doc.text('Sales Orders', 20, yPosition);
        yPosition += 10;

        const salesData = reportData.sales.orders.map(sale => {
          const totalItems = sale.items ? sale.items.reduce((sum, item) => sum + (item.quantity || 0), 0) : 0;
          return [
            sale.orderNumber || 'N/A',
            sale.customerName || 'Unknown',
            totalItems.toString(),
            new Date(sale.saleDate).toLocaleDateString(),
            `$${(sale.total || 0).toFixed(2)}`,
            sale.status || 'N/A'
          ];
        });

        if (typeof doc.autoTable === 'function') {
          doc.autoTable({
            head: [['Order #', 'Customer', 'Items Sold', 'Sale Date', 'Total Amount', 'Status']],
            body: salesData,
            startY: yPosition,
            styles: { fontSize: 9 },
            headStyles: { fillColor: [66, 139, 202] },
            alternateRowStyles: { fillColor: [245, 245, 245] }
          });
        } else {
          // Fallback: render as simple text
          doc.setFontSize(10);
          doc.setFont('helvetica', 'normal');
          salesData.forEach(row => {
            if (yPosition > 270) {
              doc.addPage();
              yPosition = 20;
            }
            doc.text(`• Order: ${row[0]} - Customer: ${row[1]} - Items: ${row[2]} - Total: ${row[4]} - Date: ${row[3]}`, 20, yPosition);
            yPosition += 6;
          });
        }
      }

      // Generate the PDF as a blob
      const pdfBlob = doc.output('blob');
      const pdfArrayBuffer = await pdfBlob.arrayBuffer();
      const pdfBase64 = btoa(String.fromCharCode(...new Uint8Array(pdfArrayBuffer)));
      
      // Prepare document data for saving
      const fileName = `Business_Report_${startDate}_to_${endDate}.pdf`;
      const documentData = {
        title: `Business Report - ${startDateFormatted} to ${endDateFormatted}`,
        type: 'report',
        description: `Comprehensive business report covering inventory additions and sales from ${startDateFormatted} to ${endDateFormatted}. Generated on ${generatedDate} at ${generatedTime}.`,
        dateRange: {
          startDate: startDate,
          endDate: endDate
        },
        fileData: pdfBase64,
        fileName: fileName,
        fileSize: pdfBlob.size,
        metadata: {
          totalStockAdded: reportData.summary.totalStockAdded,
          totalSalesAmount: reportData.summary.totalSalesAmount,
          totalItemsSold: reportData.summary.totalItemsSold,
          numberOfOrders: reportData.summary.numberOfOrders
        },
        tags: ['business-report', 'inventory', 'sales', 'automatic']
      };

      // Save document to backend
      try {
        const apiUrl = process.env.REACT_APP_API_URL;
        const saveResponse = await fetch(`${apiUrl}/api/documents`, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'Authorization': `Bearer ${user.token}`
          },
          body: JSON.stringify(documentData)
        });

        if (saveResponse.ok) {
          console.log('Document saved successfully to database');
          setError(''); // Clear any previous errors
          // Show success message
          setTimeout(() => {
            const successMsg = document.createElement('div');
            successMsg.style.cssText = `
              position: fixed; top: 20px; right: 20px; z-index: 1000;
              background: #10b981; color: white; padding: 12px 20px;
              border-radius: 8px; box-shadow: 0 4px 6px rgba(0,0,0,0.1);
              font-size: 14px; font-weight: 500;
            `;
            successMsg.textContent = 'Report saved to Documents successfully!';
            document.body.appendChild(successMsg);
            setTimeout(() => document.body.removeChild(successMsg), 3000);
          }, 500);
        } else {
          console.warn('Failed to save document to database, but PDF download will continue');
        }
      } catch (saveError) {
        console.warn('Error saving document to database:', saveError);
        // Continue with download even if save fails
      }

      // Download the PDF
      doc.save(fileName);
      
    } catch (error) {
      console.error('Error generating PDF:', error);
      setError(`Failed to generate PDF: ${error.message}`);
    }
  };

  const formatCurrency = (amount) => {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD'
    }).format(amount);
  };

  const formatDate = (dateString) => {
    return new Date(dateString).toLocaleDateString();
  };

  return (
    <main className="main-content" style={{ background: '#f8fafc', minHeight: '100vh', padding: '20px' }}>
      <div style={{ maxWidth: '1200px', margin: '0 auto' }}>
        {/* Header Section */}
        <div style={{ 
          display: 'flex', 
          justifyContent: 'space-between', 
          alignItems: 'flex-start',
          marginBottom: '24px',
          background: 'white',
          padding: 'clamp(16px, 3vw, 20px)',
          borderRadius: '12px',
          boxShadow: '0 1px 3px rgba(0, 0, 0, 0.1)',
          flexWrap: 'wrap',
          gap: '16px'
        }}>
          <div style={{ flex: '1', minWidth: '200px' }}>
            <h1 style={{ 
              fontSize: 'clamp(20px, 4vw, 28px)', 
              fontWeight: '600', 
              color: '#1f2937',
              margin: '0 0 8px 0',
              display: 'flex',
              alignItems: 'center',
              gap: '12px'
            }}>
              📊 Business Reports
            </h1>
            <p style={{ 
              fontSize: '14px', 
              color: '#6b7280',
              margin: '0'
            }}>
              Generate comprehensive business reports and analytics
            </p>
          </div>
        </div>

        {/* Main Content Section */}
        <div style={{ 
          backgroundColor: 'white', 
          borderRadius: '12px', 
          boxShadow: '0 1px 3px rgba(0, 0, 0, 0.1)', 
          padding: 'clamp(16px, 3vw, 24px)',
          marginBottom: '24px'
        }}>

          {/* Date Range Selection */}
          <div style={{ 
            backgroundColor: '#f8f9fa', 
            padding: 'clamp(16px, 3vw, 20px)', 
            borderRadius: '8px', 
            marginBottom: '20px' 
          }}>
            <h3 style={{ marginBottom: '15px', color: '#495057', fontSize: '16px', fontWeight: '500' }}>Select Report Period</h3>
            <div className="reports-date-selection" style={{ 
              display: 'flex', 
              gap: '15px', 
              alignItems: 'center', 
              flexWrap: 'wrap' 
            }}>
            <div>
              <label style={{ display: 'block', marginBottom: '5px', fontWeight: '500' }}>
                Start Date:
              </label>
              <input
                type="date"
                value={startDate}
                onChange={(e) => setStartDate(e.target.value)}
                style={{
                  padding: '8px 12px',
                  border: '1px solid #ddd',
                  borderRadius: '4px',
                  fontSize: '14px'
                }}
              />
            </div>
            <div>
              <label style={{ display: 'block', marginBottom: '5px', fontWeight: '500' }}>
                End Date:
              </label>
              <input
                type="date"
                value={endDate}
                onChange={(e) => setEndDate(e.target.value)}
                style={{
                  padding: '8px 12px',
                  border: '1px solid #ddd',
                  borderRadius: '4px',
                  fontSize: '14px'
                }}
              />
            </div>
            <div style={{ marginTop: '20px' }}>
              <button
                onClick={generateReport}
                disabled={loading}
                style={{
                  backgroundColor: '#007bff',
                  color: 'white',
                  border: 'none',
                  padding: '10px 20px',
                  borderRadius: '5px',
                  cursor: loading ? 'not-allowed' : 'pointer',
                  fontSize: '14px',
                  fontWeight: '500',
                  opacity: loading ? 0.6 : 1
                }}
              >
                {loading ? 'Generating...' : 'Generate Report'}
              </button>
            </div>
          </div>
        </div>

        {/* Error Message */}
        {error && (
          <div style={{
            backgroundColor: '#f8d7da',
            color: '#721c24',
            padding: '12px 16px',
            borderRadius: '4px',
            marginBottom: '20px',
            border: '1px solid #f5c6cb'
          }}>
            {error}
          </div>
        )}

        {/* Report Content */}
        {reportData && (
          <div>
              {/* Summary Cards */}
            <div className="reports-grid" style={{ 
              marginBottom: '24px' 
            }}>
              <div style={{
                background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
                color: 'white',
                padding: 'clamp(16px, 3vw, 20px)',
                borderRadius: '12px',
                textAlign: 'center',
                boxShadow: '0 1px 3px rgba(0, 0, 0, 0.1)'
              }}>
                <h3 style={{ margin: '0 0 10px 0', fontSize: '14px', opacity: 0.9 }}>Total Stock Added</h3>
                <p style={{ margin: 0, fontSize: 'clamp(20px, 4vw, 24px)', fontWeight: '600' }}>
                  {reportData.summary.totalStockAdded}
                </p>
                <small style={{ opacity: 0.8 }}>items</small>
              </div>

              <div style={{
                background: 'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)',
                color: 'white',
                padding: 'clamp(16px, 3vw, 20px)',
                borderRadius: '12px',
                textAlign: 'center',
                boxShadow: '0 1px 3px rgba(0, 0, 0, 0.1)'
              }}>
                <h3 style={{ margin: '0 0 10px 0', fontSize: '14px', opacity: 0.9 }}>Total Sales</h3>
                <p style={{ margin: 0, fontSize: 'clamp(20px, 4vw, 24px)', fontWeight: '600' }}>
                  {formatCurrency(reportData.summary.totalSalesAmount)}
                </p>
                <small style={{ opacity: 0.8 }}>revenue</small>
              </div>

              <div style={{
                background: 'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)',
                color: 'white',
                padding: 'clamp(16px, 3vw, 20px)',
                borderRadius: '12px',
                textAlign: 'center',
                boxShadow: '0 1px 3px rgba(0, 0, 0, 0.1)'
              }}>
                <h3 style={{ margin: '0 0 10px 0', fontSize: '14px', opacity: 0.9 }}>Items Sold</h3>
                <p style={{ margin: 0, fontSize: 'clamp(20px, 4vw, 24px)', fontWeight: '600' }}>
                  {reportData.summary.totalItemsSold}
                </p>
                <small style={{ opacity: 0.8 }}>units</small>
              </div>

              <div style={{
                background: 'linear-gradient(135deg, #43e97b 0%, #38f9d7 100%)',
                color: 'white',
                padding: 'clamp(16px, 3vw, 20px)',
                borderRadius: '12px',
                textAlign: 'center',
                boxShadow: '0 1px 3px rgba(0, 0, 0, 0.1)'
              }}>
                <h3 style={{ margin: '0 0 10px 0', fontSize: '14px', opacity: 0.9 }}>Orders</h3>
                <p style={{ margin: 0, fontSize: 'clamp(20px, 4vw, 24px)', fontWeight: '600' }}>
                  {reportData.summary.numberOfOrders}
                </p>
                <small style={{ opacity: 0.8 }}>completed</small>
              </div>
            </div>

            {/* Download PDF Button */}
            <div style={{ textAlign: 'center', marginBottom: '30px' }}>
              <button
                onClick={downloadPDF}
                style={{
                  backgroundColor: '#28a745',
                  color: 'white',
                  border: 'none',
                  padding: '12px 24px',
                  borderRadius: '5px',
                  cursor: 'pointer',
                  fontSize: '16px',
                  fontWeight: '500',
                  display: 'inline-flex',
                  alignItems: 'center',
                  gap: '8px'
                }}
              >
                📄 Download PDF Report
              </button>
              <p style={{ fontSize: '14px', color: '#666', marginTop: '8px' }}>
                PDF will be automatically saved to Documents for future reference
              </p>
            </div>

            {/* Stock Additions Section */}
            {((reportData.inventory.items && reportData.inventory.items.length > 0) || 
              (reportData.purchases.items && reportData.purchases.items.length > 0)) && (
              <div style={{ marginBottom: '30px' }}>
                <h3 style={{ 
                  color: '#333', 
                  marginBottom: '15px', 
                  fontSize: '20px',
                  borderBottom: '2px solid #007bff',
                  paddingBottom: '5px'
                }}>
                  📦 Stock Additions
                </h3>
                <div style={{ overflowX: 'auto' }}>
                  <table style={{ 
                    width: '100%', 
                    borderCollapse: 'collapse',
                    backgroundColor: 'white',
                    boxShadow: '0 1px 3px rgba(0,0,0,0.1)',
                    borderRadius: '8px',
                    overflow: 'hidden'
                  }}>
                    <thead>
                      <tr style={{ backgroundColor: '#f8f9fa' }}>
                        <th style={{ padding: '12px', textAlign: 'left', borderBottom: '1px solid #dee2e6' }}>Item Name</th>
                        <th style={{ padding: '12px', textAlign: 'left', borderBottom: '1px solid #dee2e6' }}>Quantity</th>
                        <th style={{ padding: '12px', textAlign: 'left', borderBottom: '1px solid #dee2e6' }}>Date Added</th>
                        <th style={{ padding: '12px', textAlign: 'left', borderBottom: '1px solid #dee2e6' }}>Supplier</th>
                        <th style={{ padding: '12px', textAlign: 'left', borderBottom: '1px solid #dee2e6' }}>Source</th>
                      </tr>
                    </thead>
                    <tbody>
                      {/* New inventory items */}
                      {reportData.inventory.items && reportData.inventory.items.map((item, index) => (
                        <tr key={`inv-${index}`} style={{ borderBottom: '1px solid #dee2e6' }}>
                          <td style={{ padding: '12px' }}>{item.name}</td>
                          <td style={{ padding: '12px' }}>{item.quantity}</td>
                          <td style={{ padding: '12px' }}>{formatDate(item.dateAdded)}</td>
                          <td style={{ padding: '12px' }}>{item.supplier || 'N/A'}</td>
                          <td style={{ padding: '12px' }}>
                            <span style={{ 
                              backgroundColor: '#e7f3ff', 
                              color: '#0066cc', 
                              padding: '2px 8px', 
                              borderRadius: '12px', 
                              fontSize: '12px' 
                            }}>
                              New Item
                            </span>
                          </td>
                        </tr>
                      ))}
                      {/* Purchase items */}
                      {reportData.purchases.items && reportData.purchases.items.map((item, index) => (
                        <tr key={`pur-${index}`} style={{ borderBottom: '1px solid #dee2e6' }}>
                          <td style={{ padding: '12px' }}>{item.name}</td>
                          <td style={{ padding: '12px' }}>{item.quantity}</td>
                          <td style={{ padding: '12px' }}>{formatDate(item.dateAdded)}</td>
                          <td style={{ padding: '12px' }}>{item.supplier || 'N/A'}</td>
                          <td style={{ padding: '12px' }}>
                            <span style={{ 
                              backgroundColor: '#f0f9ff', 
                              color: '#0891b2', 
                              padding: '2px 8px', 
                              borderRadius: '12px', 
                              fontSize: '12px' 
                            }}>
                              Purchase
                            </span>
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            )}

            {/* Sales Section */}
            {reportData.sales.orders && reportData.sales.orders.length > 0 && (
              <div>
                <h3 style={{ 
                  color: '#333', 
                  marginBottom: '15px', 
                  fontSize: '20px',
                  borderBottom: '2px solid #28a745',
                  paddingBottom: '5px'
                }}>
                  💰 Sales Orders
                </h3>
                <div style={{ overflowX: 'auto' }}>
                  <table style={{ 
                    width: '100%', 
                    borderCollapse: 'collapse',
                    backgroundColor: 'white',
                    boxShadow: '0 1px 3px rgba(0,0,0,0.1)',
                    borderRadius: '8px',
                    overflow: 'hidden'
                  }}>
                    <thead>
                      <tr style={{ backgroundColor: '#f8f9fa' }}>
                        <th style={{ padding: '12px', textAlign: 'left', borderBottom: '1px solid #dee2e6' }}>Order Number</th>
                        <th style={{ padding: '12px', textAlign: 'left', borderBottom: '1px solid #dee2e6' }}>Customer</th>
                        <th style={{ padding: '12px', textAlign: 'left', borderBottom: '1px solid #dee2e6' }}>Items Sold</th>
                        <th style={{ padding: '12px', textAlign: 'left', borderBottom: '1px solid #dee2e6' }}>Sale Date</th>
                        <th style={{ padding: '12px', textAlign: 'left', borderBottom: '1px solid #dee2e6' }}>Total Amount</th>
                        <th style={{ padding: '12px', textAlign: 'left', borderBottom: '1px solid #dee2e6' }}>Status</th>
                      </tr>
                    </thead>
                    <tbody>
                      {reportData.sales.orders.map((sale, index) => {
                        const totalItems = sale.items ? sale.items.reduce((sum, item) => sum + item.quantity, 0) : 0;
                        return (
                          <tr key={index} style={{ borderBottom: '1px solid #dee2e6' }}>
                            <td style={{ padding: '12px' }}>{sale.orderNumber}</td>
                            <td style={{ padding: '12px' }}>{sale.customerName}</td>
                            <td style={{ padding: '12px' }}>{totalItems}</td>
                            <td style={{ padding: '12px' }}>{formatDate(sale.saleDate)}</td>
                            <td style={{ padding: '12px', fontWeight: 'bold' }}>{formatCurrency(sale.total)}</td>
                            <td style={{ padding: '12px' }}>
                              <span style={{ 
                                backgroundColor: sale.status === 'completed' ? '#d4edda' : '#fff3cd', 
                                color: sale.status === 'completed' ? '#155724' : '#856404', 
                                padding: '2px 8px', 
                                borderRadius: '12px', 
                                fontSize: '12px' 
                              }}>
                                {sale.status}
                              </span>
                            </td>
                          </tr>
                        );
                      })}
                    </tbody>
                  </table>
                </div>
              </div>
            )}
          </div>
        )}
        </div>
      </div>
    </main>
  );
};

export default Reports;
