import React, { useState, useEffect } from 'react';
import { useAuthContext } from '../hooks/useAuthContext';

const ReportsCDN = () => {
  const { user } = useAuthContext();
  const [startDate, setStartDate] = useState('');
  const [endDate, setEndDate] = useState('');
  const [reportData, setReportData] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [jsPDFLoaded, setJsPDFLoaded] = useState(false);

  // Load jsPDF from CDN
  useEffect(() => {
    const loadJsPDF = () => {
      // Load jsPDF from CDN
      const script1 = document.createElement('script');
      script1.src = 'https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js';
      script1.onload = () => {
        // Load autoTable plugin
        const script2 = document.createElement('script');
        script2.src = 'https://cdnjs.cloudflare.com/ajax/libs/jspdf-autotable/3.5.31/jspdf.plugin.autotable.min.js';
        script2.onload = () => {
          setJsPDFLoaded(true);
          console.log('jsPDF and autoTable loaded from CDN');
        };
        script2.onerror = () => {
          console.error('Failed to load autoTable plugin');
          setJsPDFLoaded(true); // Still allow basic PDF functionality
        };
        document.head.appendChild(script2);
      };
      script1.onerror = () => {
        console.error('Failed to load jsPDF');
        setError('Failed to load PDF library. Please refresh the page.');
      };
      document.head.appendChild(script1);
    };

    if (!window.jspdf) {
      loadJsPDF();
    } else {
      setJsPDFLoaded(true);
    }
  }, []);

  // Check if user is admin
  if (!user || user.role !== 'admin') {
    return (
      <div className="reports-container" style={{ padding: '20px', textAlign: 'center' }}>
        <h2>Access Denied</h2>
        <p>Only administrators can access reports.</p>
      </div>
    );
  }

  const generateReport = async () => {
    if (!startDate || !endDate) {
      setError('Please select both start and end dates');
      return;
    }

    if (new Date(startDate) > new Date(endDate)) {
      setError('Start date cannot be greater than end date');
      return;
    }

    setLoading(true);
    setError('');

    try {
      const apiUrl = process.env.REACT_APP_API_URL;
      const response = await fetch(`${apiUrl}/api/reports?startDate=${startDate}&endDate=${endDate}`, {
        headers: {
          'Authorization': `Bearer ${user.token}`
        }
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.error || 'Failed to generate report');
      }

      const data = await response.json();
      setReportData(data);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  const downloadPDF = () => {
    if (!reportData) {
      setError('No report data available to download');
      return;
    }

    if (!jsPDFLoaded || !window.jspdf) {
      setError('PDF library is still loading. Please try again in a moment.');
      return;
    }

    try {
      const { jsPDF } = window.jspdf;
      const doc = new jsPDF();
      
      // Company header
      doc.setFontSize(20);
      doc.setFont('helvetica', 'bold');
      doc.text('Inventory Management System', 105, 20, { align: 'center' });
      
      doc.setFontSize(16);
      doc.setFont('helvetica', 'normal');
      doc.text('Business Report', 105, 30, { align: 'center' });
      
      // Report details
      doc.setFontSize(12);
      const startDateFormatted = new Date(startDate).toLocaleDateString();
      const endDateFormatted = new Date(endDate).toLocaleDateString();
      const generatedDate = new Date().toLocaleDateString();
      const generatedTime = new Date().toLocaleTimeString();
      
      doc.text(`Report Period: ${startDateFormatted} - ${endDateFormatted}`, 20, 45);
      doc.text(`Generated on: ${generatedDate} at ${generatedTime}`, 20, 55);
      doc.text(`Generated by: ${user.name || 'Admin'}`, 20, 65);

      let yPosition = 80;

      // Summary Section
      doc.setFontSize(14);
      doc.setFont('helvetica', 'bold');
      doc.text('Summary', 20, yPosition);
      yPosition += 10;

      doc.setFontSize(11);
      doc.setFont('helvetica', 'normal');
      doc.text(`Total Stock Added: ${reportData.summary.totalStockAdded} items`, 20, yPosition);
      yPosition += 7;
      doc.text(`Total Sales Amount: S$${reportData.summary.totalSalesAmount.toFixed(2)}`, 20, yPosition);
      yPosition += 7;
      doc.text(`Total Items Sold: ${reportData.summary.totalItemsSold}`, 20, yPosition);
      yPosition += 7;
      doc.text(`Number of Orders: ${reportData.summary.numberOfOrders}`, 20, yPosition);
      yPosition += 15;

      // Stock Additions Section
      const totalStockItems = (reportData.inventory.items?.length || 0) + (reportData.purchases.items?.length || 0);
      
      if (totalStockItems > 0) {
        doc.setFontSize(14);
        doc.setFont('helvetica', 'bold');
        doc.text('Stock Additions', 20, yPosition);
        yPosition += 10;

        const stockData = [];
        
        // Add inventory items
        if (reportData.inventory.items && reportData.inventory.items.length > 0) {
          reportData.inventory.items.forEach(item => {
            stockData.push([
              item.name || 'Unknown',
              (item.quantity || 0).toString(),
              new Date(item.dateAdded).toLocaleDateString(),
              item.supplier || 'N/A',
              'New Item'
            ]);
          });
        }
        
        // Add purchase items
        if (reportData.purchases.items && reportData.purchases.items.length > 0) {
          reportData.purchases.items.forEach(item => {
            stockData.push([
              item.name || 'Unknown',
              (item.quantity || 0).toString(),
              new Date(item.dateAdded).toLocaleDateString(),
              item.supplier || 'N/A',
              'Purchase'
            ]);
          });
        }

        if (stockData.length > 0) {
          // Check if autoTable is available
          if (typeof doc.autoTable === 'function') {
            doc.autoTable({
              head: [['Item Name', 'Quantity', 'Date Added', 'Supplier', 'Type']],
              body: stockData,
              startY: yPosition,
              styles: { fontSize: 9 },
              headStyles: { fillColor: [66, 139, 202] },
              alternateRowStyles: { fillColor: [245, 245, 245] }
            });
            yPosition = doc.lastAutoTable.finalY + 15;
          } else {
            // Fallback: render as simple text if autoTable is not available
            doc.setFontSize(10);
            doc.setFont('helvetica', 'normal');
            stockData.forEach(row => {
              if (yPosition > 270) {
                doc.addPage();
                yPosition = 20;
              }
              doc.text(`• ${row[0]} - Qty: ${row[1]} - Date: ${row[2]} - Type: ${row[4]}`, 20, yPosition);
              yPosition += 6;
            });
            yPosition += 10;
          }
        }
      }

      // Check if we need a new page
      if (yPosition > 250) {
        doc.addPage();
        yPosition = 20;
      }

      // Sales Section
      if (reportData.sales.orders && reportData.sales.orders.length > 0) {
        doc.setFontSize(14);
        doc.setFont('helvetica', 'bold');
        doc.text('Sales Orders', 20, yPosition);
        yPosition += 10;

        const salesData = reportData.sales.orders.map(sale => {
          const totalItems = sale.items ? sale.items.reduce((sum, item) => sum + (item.quantity || 0), 0) : 0;
          return [
            sale.orderNumber || 'N/A',
            sale.customerName || 'Unknown',
            totalItems.toString(),
            new Date(sale.saleDate).toLocaleDateString(),
            `$${(sale.total || 0).toFixed(2)}`,
            sale.status || 'N/A'
          ];
        });

        if (typeof doc.autoTable === 'function') {
          doc.autoTable({
            head: [['Order #', 'Customer', 'Items Sold', 'Sale Date', 'Total Amount', 'Status']],
            body: salesData,
            startY: yPosition,
            styles: { fontSize: 9 },
            headStyles: { fillColor: [66, 139, 202] },
            alternateRowStyles: { fillColor: [245, 245, 245] }
          });
        } else {
          // Fallback: render as simple text
          doc.setFontSize(10);
          doc.setFont('helvetica', 'normal');
          salesData.forEach(row => {
            if (yPosition > 270) {
              doc.addPage();
              yPosition = 20;
            }
            doc.text(`• Order: ${row[0]} - Customer: ${row[1]} - Items: ${row[2]} - Total: ${row[4]} - Date: ${row[3]}`, 20, yPosition);
            yPosition += 6;
          });
        }
      }

      // Save the PDF
      const fileName = `Business_Report_${startDate}_to_${endDate}.pdf`;
      doc.save(fileName);
      
    } catch (error) {
      console.error('Error generating PDF:', error);
      setError(`Failed to generate PDF: ${error.message}`);
    }
  };

  const formatCurrency = (amount) => {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD'
    }).format(amount);
  };

  const formatDate = (dateString) => {
    return new Date(dateString).toLocaleDateString();
  };

  return (
    <div className="reports-container" style={{ padding: '20px', maxWidth: '1200px', margin: '0 auto' }}>
      <div style={{ 
        backgroundColor: 'white', 
        borderRadius: '8px', 
        boxShadow: '0 2px 10px rgba(0,0,0,0.1)', 
        padding: '30px' 
      }}>
        <h2 style={{ 
          color: '#333', 
          marginBottom: '30px', 
          fontSize: '28px', 
          fontWeight: 'bold' 
        }}>
          📊 Business Reports (CDN Version)
        </h2>

        {!jsPDFLoaded && (
          <div style={{
            backgroundColor: '#fff3cd',
            color: '#856404',
            padding: '15px',
            borderRadius: '5px',
            marginBottom: '20px',
            border: '1px solid #ffeaa7'
          }}>
            Loading PDF library... Please wait.
          </div>
        )}

        {/* Date Range Selection */}
        <div style={{ 
          backgroundColor: '#f8f9fa', 
          padding: '20px', 
          borderRadius: '8px', 
          marginBottom: '20px' 
        }}>
          <h3 style={{ marginBottom: '15px', color: '#495057' }}>Select Report Period</h3>
          <div style={{ 
            display: 'flex', 
            gap: '15px', 
            alignItems: 'center', 
            flexWrap: 'wrap' 
          }}>
            <div>
              <label style={{ display: 'block', marginBottom: '5px', fontWeight: '500' }}>
                Start Date:
              </label>
              <input
                type="date"
                value={startDate}
                onChange={(e) => setStartDate(e.target.value)}
                style={{
                  padding: '8px 12px',
                  border: '1px solid #ddd',
                  borderRadius: '4px',
                  fontSize: '14px'
                }}
              />
            </div>
            <div>
              <label style={{ display: 'block', marginBottom: '5px', fontWeight: '500' }}>
                End Date:
              </label>
              <input
                type="date"
                value={endDate}
                onChange={(e) => setEndDate(e.target.value)}
                style={{
                  padding: '8px 12px',
                  border: '1px solid #ddd',
                  borderRadius: '4px',
                  fontSize: '14px'
                }}
              />
            </div>
            <div style={{ marginTop: '20px' }}>
              <button
                onClick={generateReport}
                disabled={loading}
                style={{
                  backgroundColor: '#007bff',
                  color: 'white',
                  border: 'none',
                  padding: '10px 20px',
                  borderRadius: '5px',
                  cursor: loading ? 'not-allowed' : 'pointer',
                  fontSize: '14px',
                  fontWeight: '500',
                  opacity: loading ? 0.6 : 1
                }}
              >
                {loading ? 'Generating...' : 'Generate Report'}
              </button>
            </div>
          </div>
        </div>

        {/* Error Message */}
        {error && (
          <div style={{
            backgroundColor: '#f8d7da',
            color: '#721c24',
            padding: '15px',
            borderRadius: '5px',
            marginBottom: '20px',
            border: '1px solid #f5c6cb'
          }}>
            {error}
          </div>
        )}

        {/* Report Results */}
        {reportData && (
          <div>
            {/* Summary Cards */}
            <div style={{ 
              display: 'grid', 
              gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))', 
              gap: '20px', 
              marginBottom: '30px' 
            }}>
              <div style={{
                backgroundColor: '#e3f2fd',
                padding: '20px',
                borderRadius: '8px',
                textAlign: 'center'
              }}>
                <h4 style={{ margin: '0 0 10px 0', color: '#1565c0' }}>Total Stock Added</h4>
                <p style={{ fontSize: '24px', fontWeight: 'bold', margin: 0, color: '#0d47a1' }}>
                  {reportData.summary.totalStockAdded}
                </p>
              </div>
              <div style={{
                backgroundColor: '#e8f5e8',
                padding: '20px',
                borderRadius: '8px',
                textAlign: 'center'
              }}>
                <h4 style={{ margin: '0 0 10px 0', color: '#2e7d32' }}>Total Sales</h4>
                <p style={{ fontSize: '24px', fontWeight: 'bold', margin: 0, color: '#1b5e20' }}>
                  {formatCurrency(reportData.summary.totalSalesAmount)}
                </p>
              </div>
              <div style={{
                backgroundColor: '#fff3e0',
                padding: '20px',
                borderRadius: '8px',
                textAlign: 'center'
              }}>
                <h4 style={{ margin: '0 0 10px 0', color: '#f57c00' }}>Items Sold</h4>
                <p style={{ fontSize: '24px', fontWeight: 'bold', margin: 0, color: '#e65100' }}>
                  {reportData.summary.totalItemsSold}
                </p>
              </div>
              <div style={{
                backgroundColor: '#fce4ec',
                padding: '20px',
                borderRadius: '8px',
                textAlign: 'center'
              }}>
                <h4 style={{ margin: '0 0 10px 0', color: '#c2185b' }}>Orders</h4>
                <p style={{ fontSize: '24px', fontWeight: 'bold', margin: 0, color: '#ad1457' }}>
                  {reportData.summary.numberOfOrders}
                </p>
              </div>
            </div>

            {/* Download PDF Button */}
            <div style={{ textAlign: 'center', marginBottom: '30px' }}>
              <button
                onClick={downloadPDF}
                disabled={!jsPDFLoaded}
                style={{
                  backgroundColor: jsPDFLoaded ? '#28a745' : '#6c757d',
                  color: 'white',
                  border: 'none',
                  padding: '12px 24px',
                  borderRadius: '5px',
                  cursor: jsPDFLoaded ? 'pointer' : 'not-allowed',
                  fontSize: '16px',
                  fontWeight: '500'
                }}
              >
                📄 {jsPDFLoaded ? 'Download PDF Report' : 'Loading PDF Library...'}
              </button>
            </div>

            {/* Rest of the component remains the same as the original Reports component */}
            {/* ... (Stock Additions and Sales sections) ... */}
          </div>
        )}
      </div>
    </div>
  );
};

export default ReportsCDN;
