import React, { useState } from 'react';
import { useAuthContext } from '../hooks/useAuthContext';
import jsPDF from 'jspdf';
import 'jspdf-autotable';

const Reports = () => {
  const { user } = useAuthContext();
  const [startDate, setStartDate] = useState('');
  const [endDate, setEndDate] = useState('');
  const [reportData, setReportData] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  // Check if user is admin
  if (!user || user.role !== 'admin') {
    return (
      <div className="reports-container" style={{ padding: '20px', textAlign: 'center' }}>
        <h2>Access Denied</h2>
        <p>Only administrators can access reports.</p>
      </div>
    );
  }

  const generateReport = async () => {
    if (!startDate || !endDate) {
      setError('Please select both start and end dates');
      return;
    }

    if (new Date(startDate) > new Date(endDate)) {
      setError('Start date cannot be greater than end date');
      return;
    }

    setLoading(true);
    setError('');

    try {
      const apiUrl = process.env.REACT_APP_API_URL;
      const response = await fetch(`${apiUrl}/api/reports?startDate=${startDate}&endDate=${endDate}`, {
        headers: {
          'Authorization': `Bearer ${user.token}`
        }
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.error || 'Failed to generate report');
      }

      const data = await response.json();
      setReportData(data);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  const downloadPDF = () => {
    if (!reportData) {
      setError('No report data available to download');
      return;
    }

    try {
      // Create new PDF document
      const doc = new jsPDF();
      const pageWidth = doc.internal.pageSize.getWidth();
      
      // Company header
      doc.setFontSize(20);
      doc.setFont('helvetica', 'bold');
      doc.text('Inventory Management System', pageWidth / 2, 20, { align: 'center' });
      
      doc.setFontSize(16);
      doc.setFont('helvetica', 'normal');
      doc.text('Business Report', pageWidth / 2, 30, { align: 'center' });
      
      // Report details
      doc.setFontSize(12);
      const startDateFormatted = new Date(startDate).toLocaleDateString();
      const endDateFormatted = new Date(endDate).toLocaleDateString();
      const generatedDate = new Date().toLocaleDateString();
      const generatedTime = new Date().toLocaleTimeString();
      
      doc.text(`Report Period: ${startDateFormatted} - ${endDateFormatted}`, 20, 45);
      doc.text(`Generated on: ${generatedDate} at ${generatedTime}`, 20, 55);
      doc.text(`Generated by: ${user.name || 'Admin'}`, 20, 65);

      let yPosition = 80;

      // Summary Section
      doc.setFontSize(14);
      doc.setFont('helvetica', 'bold');
      doc.text('Summary', 20, yPosition);
      yPosition += 10;

      doc.setFontSize(11);
      doc.setFont('helvetica', 'normal');
      doc.text(`Total Stock Added: ${reportData.summary.totalStockAdded} items`, 20, yPosition);
      yPosition += 7;
      doc.text(`Total Sales Amount: S$${reportData.summary.totalSalesAmount.toFixed(2)}`, 20, yPosition);
      yPosition += 7;
      doc.text(`Total Items Sold: ${reportData.summary.totalItemsSold}`, 20, yPosition);
      yPosition += 7;
      doc.text(`Number of Orders: ${reportData.summary.numberOfOrders}`, 20, yPosition);
      yPosition += 15;

      // Stock Additions Section
      const totalStockItems = (reportData.inventory.items?.length || 0) + (reportData.purchases.items?.length || 0);
      
      if (totalStockItems > 0) {
        doc.setFontSize(14);
        doc.setFont('helvetica', 'bold');
        doc.text('Stock Additions', 20, yPosition);
        yPosition += 10;

        const stockData = [];
        
        // Add inventory items
        if (reportData.inventory.items && reportData.inventory.items.length > 0) {
          reportData.inventory.items.forEach(item => {
            stockData.push([
              item.name || 'Unknown',
              (item.quantity || 0).toString(),
              new Date(item.dateAdded).toLocaleDateString(),
              item.supplier || 'N/A',
              'New Item'
            ]);
          });
        }
        
        // Add purchase items
        if (reportData.purchases.items && reportData.purchases.items.length > 0) {
          reportData.purchases.items.forEach(item => {
            stockData.push([
              item.name || 'Unknown',
              (item.quantity || 0).toString(),
              new Date(item.dateAdded).toLocaleDateString(),
              item.supplier || 'N/A',
              'Purchase'
            ]);
          });
        }

        if (stockData.length > 0) {
          doc.autoTable({
            head: [['Item Name', 'Quantity', 'Date Added', 'Supplier', 'Type']],
            body: stockData,
            startY: yPosition,
            styles: { fontSize: 9 },
            headStyles: { fillColor: [66, 139, 202] },
            alternateRowStyles: { fillColor: [245, 245, 245] }
          });
          yPosition = doc.lastAutoTable.finalY + 15;
        }
      }

      // Check if we need a new page
      if (yPosition > 250) {
        doc.addPage();
        yPosition = 20;
      }

      // Sales Section
      if (reportData.sales.orders && reportData.sales.orders.length > 0) {
        doc.setFontSize(14);
        doc.setFont('helvetica', 'bold');
        doc.text('Sales Orders', 20, yPosition);
        yPosition += 10;

        const salesData = reportData.sales.orders.map(sale => {
          const totalItems = sale.items ? sale.items.reduce((sum, item) => sum + (item.quantity || 0), 0) : 0;
          return [
            sale.orderNumber || 'N/A',
            sale.customerName || 'Unknown',
            totalItems.toString(),
            new Date(sale.saleDate).toLocaleDateString(),
            `$${(sale.total || 0).toFixed(2)}`,
            sale.status || 'N/A'
          ];
        });

        doc.autoTable({
          head: [['Order #', 'Customer', 'Items Sold', 'Sale Date', 'Total Amount', 'Status']],
          body: salesData,
          startY: yPosition,
          styles: { fontSize: 9 },
          headStyles: { fillColor: [66, 139, 202] },
          alternateRowStyles: { fillColor: [245, 245, 245] }
        });
      }

      // Save the PDF
      const fileName = `Business_Report_${startDate}_to_${endDate}.pdf`;
      doc.save(fileName);
      
    } catch (error) {
      console.error('Error generating PDF:', error);
      setError(`Failed to generate PDF: ${error.message}`);
    }
  };

  const formatCurrency = (amount) => {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD'
    }).format(amount);
  };

  const formatDate = (dateString) => {
    return new Date(dateString).toLocaleDateString();
  };

  return (
    <div className="reports-container" style={{ padding: '20px', maxWidth: '1200px', margin: '0 auto' }}>
      <div style={{ 
        backgroundColor: 'white', 
        borderRadius: '8px', 
        boxShadow: '0 2px 10px rgba(0,0,0,0.1)', 
        padding: '30px' 
      }}>
        <h2 style={{ 
          color: '#333', 
          marginBottom: '30px', 
          fontSize: '28px', 
          fontWeight: 'bold' 
        }}>
          📊 Business Reports
        </h2>

        {/* Date Range Selection */}
        <div style={{ 
          backgroundColor: '#f8f9fa', 
          padding: '20px', 
          borderRadius: '8px', 
          marginBottom: '20px' 
        }}>
          <h3 style={{ marginBottom: '15px', color: '#495057' }}>Select Report Period</h3>
          <div style={{ 
            display: 'flex', 
            gap: '15px', 
            alignItems: 'center', 
            flexWrap: 'wrap' 
          }}>
            <div>
              <label style={{ display: 'block', marginBottom: '5px', fontWeight: '500' }}>
                Start Date:
              </label>
              <input
                type="date"
                value={startDate}
                onChange={(e) => setStartDate(e.target.value)}
                style={{
                  padding: '8px 12px',
                  border: '1px solid #ddd',
                  borderRadius: '4px',
                  fontSize: '14px'
                }}
              />
            </div>
            <div>
              <label style={{ display: 'block', marginBottom: '5px', fontWeight: '500' }}>
                End Date:
              </label>
              <input
                type="date"
                value={endDate}
                onChange={(e) => setEndDate(e.target.value)}
                style={{
                  padding: '8px 12px',
                  border: '1px solid #ddd',
                  borderRadius: '4px',
                  fontSize: '14px'
                }}
              />
            </div>
            <div style={{ marginTop: '20px' }}>
              <button
                onClick={generateReport}
                disabled={loading}
                style={{
                  backgroundColor: '#007bff',
                  color: 'white',
                  border: 'none',
                  padding: '10px 20px',
                  borderRadius: '5px',
                  cursor: loading ? 'not-allowed' : 'pointer',
                  fontSize: '14px',
                  fontWeight: '500',
                  opacity: loading ? 0.6 : 1
                }}
              >
                {loading ? 'Generating...' : 'Generate Report'}
              </button>
            </div>
          </div>
        </div>

        {/* Error Message */}
        {error && (
          <div style={{
            backgroundColor: '#f8d7da',
            color: '#721c24',
            padding: '15px',
            borderRadius: '5px',
            marginBottom: '20px',
            border: '1px solid #f5c6cb'
          }}>
            {error}
          </div>
        )}

        {/* Report Results */}
        {reportData && (
          <div>
            {/* Summary Cards */}
            <div style={{ 
              display: 'grid', 
              gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))', 
              gap: '20px', 
              marginBottom: '30px' 
            }}>
              <div style={{
                backgroundColor: '#e3f2fd',
                padding: '20px',
                borderRadius: '8px',
                textAlign: 'center'
              }}>
                <h4 style={{ margin: '0 0 10px 0', color: '#1565c0' }}>Total Stock Added</h4>
                <p style={{ fontSize: '24px', fontWeight: 'bold', margin: 0, color: '#0d47a1' }}>
                  {reportData.summary.totalStockAdded}
                </p>
              </div>
              <div style={{
                backgroundColor: '#e8f5e8',
                padding: '20px',
                borderRadius: '8px',
                textAlign: 'center'
              }}>
                <h4 style={{ margin: '0 0 10px 0', color: '#2e7d32' }}>Total Sales</h4>
                <p style={{ fontSize: '24px', fontWeight: 'bold', margin: 0, color: '#1b5e20' }}>
                  {formatCurrency(reportData.summary.totalSalesAmount)}
                </p>
              </div>
              <div style={{
                backgroundColor: '#fff3e0',
                padding: '20px',
                borderRadius: '8px',
                textAlign: 'center'
              }}>
                <h4 style={{ margin: '0 0 10px 0', color: '#f57c00' }}>Items Sold</h4>
                <p style={{ fontSize: '24px', fontWeight: 'bold', margin: 0, color: '#e65100' }}>
                  {reportData.summary.totalItemsSold}
                </p>
              </div>
              <div style={{
                backgroundColor: '#fce4ec',
                padding: '20px',
                borderRadius: '8px',
                textAlign: 'center'
              }}>
                <h4 style={{ margin: '0 0 10px 0', color: '#c2185b' }}>Orders</h4>
                <p style={{ fontSize: '24px', fontWeight: 'bold', margin: 0, color: '#ad1457' }}>
                  {reportData.summary.numberOfOrders}
                </p>
              </div>
            </div>

            {/* Download PDF Button */}
            <div style={{ textAlign: 'center', marginBottom: '30px' }}>
              <button
                onClick={downloadPDF}
                style={{
                  backgroundColor: '#28a745',
                  color: 'white',
                  border: 'none',
                  padding: '12px 24px',
                  borderRadius: '5px',
                  cursor: 'pointer',
                  fontSize: '16px',
                  fontWeight: '500'
                }}
              >
                📄 Download PDF Report
              </button>
            </div>

            {/* Stock Additions Section */}
            <div style={{ marginBottom: '30px' }}>
              <h3 style={{ 
                color: '#495057', 
                marginBottom: '15px',
                borderBottom: '2px solid #007bff',
                paddingBottom: '5px'
              }}>
                📦 Stock Additions ({reportData.inventory.totalQuantity + reportData.purchases.totalQuantity} items)
              </h3>
              
              {(reportData.inventory.items.length === 0 && reportData.purchases.items.length === 0) ? (
                <p style={{ 
                  color: '#6c757d', 
                  fontStyle: 'italic', 
                  textAlign: 'center', 
                  padding: '20px' 
                }}>
                  No stock additions found in the selected date range.
                </p>
              ) : (
                <div style={{ overflowX: 'auto' }}>
                  <table style={{ 
                    width: '100%', 
                    borderCollapse: 'collapse', 
                    backgroundColor: 'white',
                    boxShadow: '0 1px 3px rgba(0,0,0,0.1)'
                  }}>
                    <thead>
                      <tr style={{ backgroundColor: '#f8f9fa' }}>
                        <th style={{ padding: '12px', border: '1px solid #dee2e6', textAlign: 'left' }}>Item Name</th>
                        <th style={{ padding: '12px', border: '1px solid #dee2e6', textAlign: 'left' }}>Type</th>
                        <th style={{ padding: '12px', border: '1px solid #dee2e6', textAlign: 'right' }}>Quantity</th>
                        <th style={{ padding: '12px', border: '1px solid #dee2e6', textAlign: 'left' }}>Date Added</th>
                        <th style={{ padding: '12px', border: '1px solid #dee2e6', textAlign: 'left' }}>Source</th>
                      </tr>
                    </thead>
                    <tbody>
                      {reportData.inventory.items.map((item, index) => (
                        <tr key={`inv-${index}`} style={{ borderBottom: '1px solid #dee2e6' }}>
                          <td style={{ padding: '12px', border: '1px solid #dee2e6' }}>{item.name}</td>
                          <td style={{ padding: '12px', border: '1px solid #dee2e6' }}>{item.type}</td>
                          <td style={{ padding: '12px', border: '1px solid #dee2e6', textAlign: 'right' }}>{item.quantity}</td>
                          <td style={{ padding: '12px', border: '1px solid #dee2e6' }}>{formatDate(item.dateAdded)}</td>
                          <td style={{ padding: '12px', border: '1px solid #dee2e6' }}>
                            <span style={{ 
                              backgroundColor: '#e3f2fd', 
                              color: '#1565c0', 
                              padding: '4px 8px', 
                              borderRadius: '12px', 
                              fontSize: '12px' 
                            }}>
                              New Item
                            </span>
                          </td>
                        </tr>
                      ))}
                      {reportData.purchases.items.map((item, index) => (
                        <tr key={`pur-${index}`} style={{ borderBottom: '1px solid #dee2e6' }}>
                          <td style={{ padding: '12px', border: '1px solid #dee2e6' }}>{item.name}</td>
                          <td style={{ padding: '12px', border: '1px solid #dee2e6' }}>{item.type}</td>
                          <td style={{ padding: '12px', border: '1px solid #dee2e6', textAlign: 'right' }}>{item.quantity}</td>
                          <td style={{ padding: '12px', border: '1px solid #dee2e6' }}>{formatDate(item.dateAdded)}</td>
                          <td style={{ padding: '12px', border: '1px solid #dee2e6' }}>
                            <span style={{ 
                              backgroundColor: '#fff3e0', 
                              color: '#f57c00', 
                              padding: '4px 8px', 
                              borderRadius: '12px', 
                              fontSize: '12px' 
                            }}>
                              Purchase
                            </span>
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              )}
            </div>

            {/* Sales Section */}
            <div>
              <h3 style={{ 
                color: '#495057', 
                marginBottom: '15px',
                borderBottom: '2px solid #28a745',
                paddingBottom: '5px'
              }}>
                💰 Sales Orders ({reportData.sales.orders.length} orders)
              </h3>
              
              {reportData.sales.orders.length === 0 ? (
                <p style={{ 
                  color: '#6c757d', 
                  fontStyle: 'italic', 
                  textAlign: 'center', 
                  padding: '20px' 
                }}>
                  No sales found in the selected date range.
                </p>
              ) : (
                <div style={{ overflowX: 'auto' }}>
                  <table style={{ 
                    width: '100%', 
                    borderCollapse: 'collapse', 
                    backgroundColor: 'white',
                    boxShadow: '0 1px 3px rgba(0,0,0,0.1)'
                  }}>
                    <thead>
                      <tr style={{ backgroundColor: '#f8f9fa' }}>
                        <th style={{ padding: '12px', border: '1px solid #dee2e6', textAlign: 'left' }}>Order #</th>
                        <th style={{ padding: '12px', border: '1px solid #dee2e6', textAlign: 'left' }}>Customer</th>
                        <th style={{ padding: '12px', border: '1px solid #dee2e6', textAlign: 'left' }}>Items</th>
                        <th style={{ padding: '12px', border: '1px solid #dee2e6', textAlign: 'right' }}>Qty Sold</th>
                        <th style={{ padding: '12px', border: '1px solid #dee2e6', textAlign: 'left' }}>Sale Date</th>
                        <th style={{ padding: '12px', border: '1px solid #dee2e6', textAlign: 'right' }}>Total Amount</th>
                        <th style={{ padding: '12px', border: '1px solid #dee2e6', textAlign: 'left' }}>Status</th>
                      </tr>
                    </thead>
                    <tbody>
                      {reportData.sales.orders.map((sale, index) => (
                        <tr key={index} style={{ borderBottom: '1px solid #dee2e6' }}>
                          <td style={{ padding: '12px', border: '1px solid #dee2e6' }}>
                            {sale.orderNumber || 'N/A'}
                          </td>
                          <td style={{ padding: '12px', border: '1px solid #dee2e6' }}>{sale.customerName}</td>
                          <td style={{ padding: '12px', border: '1px solid #dee2e6' }}>
                            {sale.items.map(item => item.productName).join(', ')}
                          </td>
                          <td style={{ padding: '12px', border: '1px solid #dee2e6', textAlign: 'right' }}>
                            {sale.items.reduce((sum, item) => sum + item.quantity, 0)}
                          </td>
                          <td style={{ padding: '12px', border: '1px solid #dee2e6' }}>
                            {formatDate(sale.saleDate)}
                          </td>
                          <td style={{ padding: '12px', border: '1px solid #dee2e6', textAlign: 'right', fontWeight: 'bold' }}>
                            {formatCurrency(sale.total)}
                          </td>
                          <td style={{ padding: '12px', border: '1px solid #dee2e6' }}>
                            <span style={{ 
                              backgroundColor: sale.status === 'Delivered' ? '#d4edda' : 
                                             sale.status === 'Pending' ? '#fff3cd' : '#f8d7da',
                              color: sale.status === 'Delivered' ? '#155724' : 
                                     sale.status === 'Pending' ? '#856404' : '#721c24',
                              padding: '4px 8px', 
                              borderRadius: '12px', 
                              fontSize: '12px' 
                            }}>
                              {sale.status}
                            </span>
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              )}
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default Reports;
