import React, { useState } from 'react';
import { useAuthContext } from '../hooks/useAuthContext';

const ReportsSimple = () => {
  const { user } = useAuthContext();
  const [startDate, setStartDate] = useState('');
  const [endDate, setEndDate] = useState('');
  const [reportData, setReportData] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  // Check if user is admin
  if (!user || user.role !== 'admin') {
    return (
      <div className="reports-container" style={{ padding: '20px', textAlign: 'center' }}>
        <h2>Access Denied</h2>
        <p>Only administrators can access reports.</p>
      </div>
    );
  }

  const generateReport = async () => {
    if (!startDate || !endDate) {
      setError('Please select both start and end dates');
      return;
    }

    if (new Date(startDate) > new Date(endDate)) {
      setError('Start date cannot be greater than end date');
      return;
    }

    setLoading(true);
    setError('');

    try {
      const apiUrl = process.env.REACT_APP_API_URL;
      const response = await fetch(`${apiUrl}/api/reports?startDate=${startDate}&endDate=${endDate}`, {
        headers: {
          'Authorization': `Bearer ${user.token}`
        }
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.error || 'Failed to generate report');
      }

      const data = await response.json();
      setReportData(data);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  const downloadSimplePDF = async () => {
    if (!reportData) {
      setError('No report data available to download');
      return;
    }

    try {
      // Import jsPDF dynamically to avoid build issues
      const jsPDF = (await import('jspdf')).default;
      
      const doc = new jsPDF();
      
      // Company header
      doc.setFontSize(20);
      doc.setFont('helvetica', 'bold');
      doc.text('Inventory Management System', 105, 20, { align: 'center' });
      
      doc.setFontSize(16);
      doc.setFont('helvetica', 'normal');
      doc.text('Business Report', 105, 30, { align: 'center' });
      
      // Report details
      doc.setFontSize(12);
      const startDateFormatted = new Date(startDate).toLocaleDateString();
      const endDateFormatted = new Date(endDate).toLocaleDateString();
      const generatedDate = new Date().toLocaleDateString();
      const generatedTime = new Date().toLocaleTimeString();
      
      doc.text(`Report Period: ${startDateFormatted} - ${endDateFormatted}`, 20, 45);
      doc.text(`Generated on: ${generatedDate} at ${generatedTime}`, 20, 55);
      doc.text(`Generated by: ${user.name || 'Admin'}`, 20, 65);

      let yPosition = 80;

      // Summary Section
      doc.setFontSize(14);
      doc.setFont('helvetica', 'bold');
      doc.text('SUMMARY', 20, yPosition);
      yPosition += 10;

      doc.setFontSize(11);
      doc.setFont('helvetica', 'normal');
      doc.text(`Total Stock Added: ${reportData.summary.totalStockAdded} items`, 20, yPosition);
      yPosition += 7;
      doc.text(`Total Sales Amount: $${reportData.summary.totalSalesAmount.toFixed(2)}`, 20, yPosition);
      yPosition += 7;
      doc.text(`Total Items Sold: ${reportData.summary.totalItemsSold}`, 20, yPosition);
      yPosition += 7;
      doc.text(`Number of Orders: ${reportData.summary.numberOfOrders}`, 20, yPosition);
      yPosition += 20;

      // Stock Additions Section (simplified text format)
      const totalStockItems = (reportData.inventory.items?.length || 0) + (reportData.purchases.items?.length || 0);
      
      if (totalStockItems > 0) {
        doc.setFontSize(14);
        doc.setFont('helvetica', 'bold');
        doc.text('STOCK ADDITIONS', 20, yPosition);
        yPosition += 10;

        doc.setFontSize(10);
        doc.setFont('helvetica', 'normal');
        
        // Add inventory items
        if (reportData.inventory.items && reportData.inventory.items.length > 0) {
          reportData.inventory.items.forEach(item => {
            if (yPosition > 270) {
              doc.addPage();
              yPosition = 20;
            }
            doc.text(`• ${item.name || 'Unknown'} - Qty: ${item.quantity || 0} - Date: ${new Date(item.dateAdded).toLocaleDateString()} - Type: New Item`, 20, yPosition);
            yPosition += 6;
          });
        }
        
        // Add purchase items
        if (reportData.purchases.items && reportData.purchases.items.length > 0) {
          reportData.purchases.items.forEach(item => {
            if (yPosition > 270) {
              doc.addPage();
              yPosition = 20;
            }
            doc.text(`• ${item.name || 'Unknown'} - Qty: ${item.quantity || 0} - Date: ${new Date(item.dateAdded).toLocaleDateString()} - Type: Purchase`, 20, yPosition);
            yPosition += 6;
          });
        }
        
        yPosition += 15;
      }

      // Sales Section (simplified text format)
      if (reportData.sales.orders && reportData.sales.orders.length > 0) {
        if (yPosition > 220) {
          doc.addPage();
          yPosition = 20;
        }
        
        doc.setFontSize(14);
        doc.setFont('helvetica', 'bold');
        doc.text('SALES ORDERS', 20, yPosition);
        yPosition += 10;

        doc.setFontSize(10);
        doc.setFont('helvetica', 'normal');
        
        reportData.sales.orders.forEach(sale => {
          if (yPosition > 270) {
            doc.addPage();
            yPosition = 20;
          }
          const totalItems = sale.items ? sale.items.reduce((sum, item) => sum + (item.quantity || 0), 0) : 0;
          doc.text(`• Order: ${sale.orderNumber || 'N/A'} - Customer: ${sale.customerName || 'Unknown'}`, 20, yPosition);
          yPosition += 5;
          doc.text(`  Items: ${totalItems} - Total: $${(sale.total || 0).toFixed(2)} - Date: ${new Date(sale.saleDate).toLocaleDateString()} - Status: ${sale.status || 'N/A'}`, 20, yPosition);
          yPosition += 8;
        });
      }

      // Save the PDF
      const fileName = `Business_Report_Simple_${startDate}_to_${endDate}.pdf`;
      doc.save(fileName);
      
    } catch (error) {
      console.error('Error generating simple PDF:', error);
      setError(`Failed to generate PDF: ${error.message}`);
    }
  };

  const formatCurrency = (amount) => {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD'
    }).format(amount);
  };

  const formatDate = (dateString) => {
    return new Date(dateString).toLocaleDateString();
  };

  return (
    <div className="reports-container" style={{ padding: '20px', maxWidth: '1200px', margin: '0 auto' }}>
      <div style={{ 
        backgroundColor: 'white', 
        borderRadius: '8px', 
        boxShadow: '0 2px 10px rgba(0,0,0,0.1)', 
        padding: '30px' 
      }}>
        <h2 style={{ 
          color: '#333', 
          marginBottom: '30px', 
          fontSize: '28px', 
          fontWeight: 'bold' 
        }}>
          📊 Business Reports (Simple Version)
        </h2>

        {/* Date Range Selection */}
        <div style={{ 
          backgroundColor: '#f8f9fa', 
          padding: '20px', 
          borderRadius: '8px', 
          marginBottom: '20px' 
        }}>
          <h3 style={{ marginBottom: '15px', color: '#495057' }}>Select Report Period</h3>
          <div style={{ 
            display: 'flex', 
            gap: '15px', 
            alignItems: 'center', 
            flexWrap: 'wrap' 
          }}>
            <div>
              <label style={{ display: 'block', marginBottom: '5px', fontWeight: '500' }}>
                Start Date:
              </label>
              <input
                type="date"
                value={startDate}
                onChange={(e) => setStartDate(e.target.value)}
                style={{
                  padding: '8px 12px',
                  border: '1px solid #ddd',
                  borderRadius: '4px',
                  fontSize: '14px'
                }}
              />
            </div>
            <div>
              <label style={{ display: 'block', marginBottom: '5px', fontWeight: '500' }}>
                End Date:
              </label>
              <input
                type="date"
                value={endDate}
                onChange={(e) => setEndDate(e.target.value)}
                style={{
                  padding: '8px 12px',
                  border: '1px solid #ddd',
                  borderRadius: '4px',
                  fontSize: '14px'
                }}
              />
            </div>
            <div style={{ marginTop: '20px' }}>
              <button
                onClick={generateReport}
                disabled={loading}
                style={{
                  backgroundColor: '#007bff',
                  color: 'white',
                  border: 'none',
                  padding: '10px 20px',
                  borderRadius: '5px',
                  cursor: loading ? 'not-allowed' : 'pointer',
                  fontSize: '14px',
                  fontWeight: '500',
                  opacity: loading ? 0.6 : 1
                }}
              >
                {loading ? 'Generating...' : 'Generate Report'}
              </button>
            </div>
          </div>
        </div>

        {/* Error Message */}
        {error && (
          <div style={{
            backgroundColor: '#f8d7da',
            color: '#721c24',
            padding: '15px',
            borderRadius: '5px',
            marginBottom: '20px',
            border: '1px solid #f5c6cb'
          }}>
            {error}
          </div>
        )}

        {/* Report Results */}
        {reportData && (
          <div>
            {/* Summary Cards */}
            <div style={{ 
              display: 'grid', 
              gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))', 
              gap: '20px', 
              marginBottom: '30px' 
            }}>
              <div style={{
                backgroundColor: '#e3f2fd',
                padding: '20px',
                borderRadius: '8px',
                textAlign: 'center'
              }}>
                <h4 style={{ margin: '0 0 10px 0', color: '#1565c0' }}>Total Stock Added</h4>
                <p style={{ fontSize: '24px', fontWeight: 'bold', margin: 0, color: '#0d47a1' }}>
                  {reportData.summary.totalStockAdded}
                </p>
              </div>
              <div style={{
                backgroundColor: '#e8f5e8',
                padding: '20px',
                borderRadius: '8px',
                textAlign: 'center'
              }}>
                <h4 style={{ margin: '0 0 10px 0', color: '#2e7d32' }}>Total Sales</h4>
                <p style={{ fontSize: '24px', fontWeight: 'bold', margin: 0, color: '#1b5e20' }}>
                  {formatCurrency(reportData.summary.totalSalesAmount)}
                </p>
              </div>
              <div style={{
                backgroundColor: '#fff3e0',
                padding: '20px',
                borderRadius: '8px',
                textAlign: 'center'
              }}>
                <h4 style={{ margin: '0 0 10px 0', color: '#f57c00' }}>Items Sold</h4>
                <p style={{ fontSize: '24px', fontWeight: 'bold', margin: 0, color: '#e65100' }}>
                  {reportData.summary.totalItemsSold}
                </p>
              </div>
              <div style={{
                backgroundColor: '#fce4ec',
                padding: '20px',
                borderRadius: '8px',
                textAlign: 'center'
              }}>
                <h4 style={{ margin: '0 0 10px 0', color: '#c2185b' }}>Orders</h4>
                <p style={{ fontSize: '24px', fontWeight: 'bold', margin: 0, color: '#ad1457' }}>
                  {reportData.summary.numberOfOrders}
                </p>
              </div>
            </div>

            {/* Download PDF Button */}
            <div style={{ textAlign: 'center', marginBottom: '30px' }}>
              <button
                onClick={downloadSimplePDF}
                style={{
                  backgroundColor: '#28a745',
                  color: 'white',
                  border: 'none',
                  padding: '12px 24px',
                  borderRadius: '5px',
                  cursor: 'pointer',
                  fontSize: '16px',
                  fontWeight: '500'
                }}
              >
                📄 Download Simple PDF Report
              </button>
            </div>

            {/* Stock Additions Section */}
            <div style={{ marginBottom: '30px' }}>
              <h3 style={{ 
                color: '#495057', 
                marginBottom: '15px',
                borderBottom: '2px solid #007bff',
                paddingBottom: '5px'
              }}>
                📦 Stock Additions ({reportData.inventory.totalQuantity + reportData.purchases.totalQuantity} items)
              </h3>
              
              {(reportData.inventory.items.length === 0 && reportData.purchases.items.length === 0) ? (
                <p style={{ 
                  color: '#6c757d', 
                  fontStyle: 'italic', 
                  textAlign: 'center', 
                  padding: '20px' 
                }}>
                  No stock additions found in the selected date range.
                </p>
              ) : (
                <div>
                  {/* Inventory Items */}
                  {reportData.inventory.items.map((item, index) => (
                    <div key={`inv-${index}`} style={{ 
                      padding: '10px', 
                      margin: '5px 0', 
                      backgroundColor: '#f8f9fa', 
                      borderRadius: '5px',
                      borderLeft: '4px solid #007bff'
                    }}>
                      <strong>{item.name}</strong> - {item.type} - Qty: {item.quantity} - Added: {formatDate(item.dateAdded)} - <span style={{color: '#007bff'}}>New Item</span>
                    </div>
                  ))}
                  
                  {/* Purchase Items */}
                  {reportData.purchases.items.map((item, index) => (
                    <div key={`pur-${index}`} style={{ 
                      padding: '10px', 
                      margin: '5px 0', 
                      backgroundColor: '#fff3e0', 
                      borderRadius: '5px',
                      borderLeft: '4px solid #f57c00'
                    }}>
                      <strong>{item.name}</strong> - {item.type} - Qty: {item.quantity} - Added: {formatDate(item.dateAdded)} - <span style={{color: '#f57c00'}}>Purchase</span>
                    </div>
                  ))}
                </div>
              )}
            </div>

            {/* Sales Section */}
            <div>
              <h3 style={{ 
                color: '#495057', 
                marginBottom: '15px',
                borderBottom: '2px solid #28a745',
                paddingBottom: '5px'
              }}>
                💰 Sales Orders ({reportData.sales.orders.length} orders)
              </h3>
              
              {reportData.sales.orders.length === 0 ? (
                <p style={{ 
                  color: '#6c757d', 
                  fontStyle: 'italic', 
                  textAlign: 'center', 
                  padding: '20px' 
                }}>
                  No sales found in the selected date range.
                </p>
              ) : (
                <div>
                  {reportData.sales.orders.map((sale, index) => (
                    <div key={index} style={{ 
                      padding: '15px', 
                      margin: '10px 0', 
                      backgroundColor: '#e8f5e8', 
                      borderRadius: '5px',
                      borderLeft: '4px solid #28a745'
                    }}>
                      <div style={{ marginBottom: '5px' }}>
                        <strong>Order #{sale.orderNumber || 'N/A'}</strong> - {sale.customerName}
                      </div>
                      <div style={{ fontSize: '14px', color: '#666' }}>
                        Items: {sale.items.map(item => `${item.productName} (${item.quantity})`).join(', ')}
                      </div>
                      <div style={{ fontSize: '14px', color: '#666' }}>
                        Total: <strong>{formatCurrency(sale.total)}</strong> - Date: {formatDate(sale.saleDate)} - Status: {sale.status}
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default ReportsSimple;
