// Simple PDF Generation Function - Fallback without autoTable
export const generateSimplePDF = (reportData, startDate, endDate, userName) => {
  const jsPDF = window.jspdf.jsPDF;
  const doc = new jsPDF();
  
  try {
    // Company header
    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.text('Inventory Management System', 105, 20, { align: 'center' });
    
    doc.setFontSize(16);
    doc.setFont('helvetica', 'normal');
    doc.text('Business Report', 105, 30, { align: 'center' });
    
    // Report details
    doc.setFontSize(12);
    const startDateFormatted = new Date(startDate).toLocaleDateString();
    const endDateFormatted = new Date(endDate).toLocaleDateString();
    const generatedDate = new Date().toLocaleDateString();
    const generatedTime = new Date().toLocaleTimeString();
    
    doc.text(`Report Period: ${startDateFormatted} - ${endDateFormatted}`, 20, 45);
    doc.text(`Generated on: ${generatedDate} at ${generatedTime}`, 20, 55);
    doc.text(`Generated by: ${userName || 'Admin'}`, 20, 65);

    let yPosition = 80;

    // Summary Section
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Summary', 20, yPosition);
    yPosition += 10;

    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    doc.text(`Total Stock Added: ${reportData.summary.totalStockAdded} items`, 20, yPosition);
    yPosition += 7;
    doc.text(`Total Sales Amount: S$${reportData.summary.totalSalesAmount.toFixed(2)}`, 20, yPosition);
    yPosition += 7;
    doc.text(`Total Items Sold: ${reportData.summary.totalItemsSold}`, 20, yPosition);
    yPosition += 7;
    doc.text(`Number of Orders: ${reportData.summary.numberOfOrders}`, 20, yPosition);
    yPosition += 20;

    // Stock Additions Section (simplified)
    const totalStockItems = (reportData.inventory.items?.length || 0) + (reportData.purchases.items?.length || 0);
    
    if (totalStockItems > 0) {
      doc.setFontSize(14);
      doc.setFont('helvetica', 'bold');
      doc.text('Stock Additions', 20, yPosition);
      yPosition += 10;

      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      
      // Add inventory items
      if (reportData.inventory.items && reportData.inventory.items.length > 0) {
        reportData.inventory.items.forEach(item => {
          if (yPosition > 270) {
            doc.addPage();
            yPosition = 20;
          }
          doc.text(`• ${item.name || 'Unknown'} - Qty: ${item.quantity || 0} - Date: ${new Date(item.dateAdded).toLocaleDateString()} - Type: New Item`, 20, yPosition);
          yPosition += 6;
        });
      }
      
      // Add purchase items
      if (reportData.purchases.items && reportData.purchases.items.length > 0) {
        reportData.purchases.items.forEach(item => {
          if (yPosition > 270) {
            doc.addPage();
            yPosition = 20;
          }
          doc.text(`• ${item.name || 'Unknown'} - Qty: ${item.quantity || 0} - Date: ${new Date(item.dateAdded).toLocaleDateString()} - Type: Purchase`, 20, yPosition);
          yPosition += 6;
        });
      }
      
      yPosition += 10;
    }

    // Sales Section (simplified)
    if (reportData.sales.orders && reportData.sales.orders.length > 0) {
      if (yPosition > 220) {
        doc.addPage();
        yPosition = 20;
      }
      
      doc.setFontSize(14);
      doc.setFont('helvetica', 'bold');
      doc.text('Sales Orders', 20, yPosition);
      yPosition += 10;

      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      
      reportData.sales.orders.forEach(sale => {
        if (yPosition > 270) {
          doc.addPage();
          yPosition = 20;
        }
        const totalItems = sale.items ? sale.items.reduce((sum, item) => sum + (item.quantity || 0), 0) : 0;
        doc.text(`• Order: ${sale.orderNumber || 'N/A'} - Customer: ${sale.customerName || 'Unknown'} - Items: ${totalItems} - Total: S$${(sale.total || 0).toFixed(2)} - Date: ${new Date(sale.saleDate).toLocaleDateString()}`, 20, yPosition);
        yPosition += 6;
      });
    }

    // Save the PDF
    const fileName = `Business_Report_${startDate}_to_${endDate}.pdf`;
    doc.save(fileName);
    
    return true;
  } catch (error) {
    console.error('Error generating simple PDF:', error);
    throw error;
  }
};
